CREATE DATABASE IF NOT EXISTS pixknit CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pixknit;

CREATE TABLE users(
id  INT AUTO_INCREMENT PRIMARY KEY,
pseudo VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
pp VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE patrons(
id  INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
titre VARCHAR(100) NOT NULL,
description TEXT,
grille_json LONGTEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
tags VARCHAR(255),
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE likes(
    user_id INT NOT NULL,
    patron_id INT NOT NULL,
    PRIMARY KEY (user_id, patron_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (patron_id) REFERENCES patrons(id) ON DELETE CASCADE
);

CREATE TABLE commentaires(
    id INT AUTO_INCREMENT PRIMARY KEY,
    patron_id INT NOT NULL,
    user_id INT NOT NULL,
    contenu TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patron_id) REFERENCES patrons(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
